### ISSUE TITLE
電子郵件自動回復

### ISSUE THREAD

**Issue by yurenju** [bifrostio/bifrost#116]
寄信跟他說系統有收到他的捐物登錄

**Comment by antyo** [comment]
受理捐物單位收到物資後也寄信。

另外有串簡訊的可能性嗎？市府有簡訊平台。

**Comment by antyo** [comment]
我們有點苦惱的是【捐物收據】這件事，
照道理說捐物應該要開收據，但災害時不一定會逐筆開，而且捐物抵稅非常困難，要檢據原來的發票或進貨成本，所以一般人拿到捐物收據也沒用，希望用電子郵件通知替代捐物收據，真的需要收據的人在填單的時候幫我們打個勾，我們另外掛號寄給他。

附帶出現一個功能是要可以下載【需要捐物收據的人】，讓我們批次寄收據給他。(確認社福系統格式欄位後告知格式)

**Comment by yurenju** [comment]
功能已經做完了（寄送 email），如果需要寄送簡訊或是捐物收據可以開另外一個 issue
